# Generated by Django 4.0.6 on 2022-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=10)),
                ('native_name', models.CharField(max_length=50, unique=True)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('busy', models.BooleanField()),
            ],
        ),
    ]
