# Generated by Django 4.0.6 on 2022-07-13 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0002_menuitem_reciepe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('table_num', models.IntegerField()),
                ('total', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('card', 'CARD'), ('cash', 'CASH'), ('upi', 'UPI'), ('coupons', 'CPOUPONS')], default='card', max_length=7)),
                ('delievery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
