# Generated by Django 4.0.6 on 2022-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_alter_orders_delievery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='prep_time',
            field=models.CharField(default='30m', max_length=3),
        ),
    ]
