# Generated by Django 4.0.6 on 2022-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_orders_is_accepted_orders_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_cancelled_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
