# Generated by Django 4.0.6 on 2022-07-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0006_orders_is_cancelled_by_user_alter_orders_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(related_name='menu_item', to='Menu.menuitem'),
        ),
    ]
