# Generated by Django 4.0.6 on 2022-07-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_orders_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
    ]
